// Pruebas del servidor (sin navegador): registro, entrada, guardar, conflictos, límites y entrenador.
import { spawn } from 'node:child_process';
const port = 8790, base = 'http://localhost:' + port, srv = spawn('node', [new URL('./servidor_prueba.mjs', import.meta.url).pathname, '.', String(port)], { stdio: 'ignore' });
await new Promise(r => setTimeout(r, 700));
let fails = 0; const ok = (n, c, x = '') => { console.log((c ? 'OK    ' : 'FALLA ') + n + (c ? '' : '  → ' + x)); if (!c) fails++; };
const api = async b => (await fetch(base + '/api', { method: 'POST', body: JSON.stringify(b) })).json();
const A = 'a'.repeat(64), B = 'b'.repeat(64), ADM = 'c'.repeat(64);
try {
  ok('sin configurar: no hay clave pública', (await api({ op: 'pub' })).err === 'sin_configurar');
  ok('operación desconocida', (await api({ op: 'constructor' })).err === 'op' && (await api({ op: 'nada' })).err === 'op');
  const setup = await (await fetch(base + '/__setup')).text();
  ok('puesta en marcha: código malo', (await api({ op: 'a_setup', setup: 'x', auth: ADM, salt: 's', pub: '{}', priv: 'p', kid: 'k1' })).err === 'codigo');
  const st = await api({ op: 'a_setup', setup, auth: ADM, salt: 's1', pub: '{"kty":"RSA"}', priv: 'PRIV', kid: 'k1' });
  ok('puesta en marcha con el código', st.ok && !!st.token);
  ok('el código solo sirve una vez', (await api({ op: 'a_setup', setup, auth: ADM, salt: 's', pub: '{}', priv: 'p', kid: 'k2' })).err === 'codigo');
  const hello = await api({ op: 'a_hello' }); ok('a_hello', hello.configured === true && hello.salt === 's1');
  ok('entrenador: contraseña mala', (await api({ op: 'a_login', auth: B })).err === 'credenciales');
  const al = await api({ op: 'a_login', auth: ADM }); ok('entrenador: entra y recibe su llave cifrada', al.ok && al.priv === 'PRIV' && al.kid === 'k1');
  const inv = await api({ op: 'a_invite', token: al.token, n: 3 }); ok('3 invitaciones', inv.ok && inv.codes.length === 3 && /^EP-[A-Z2-9]{4}-[A-Z2-9]{4}$/.test(inv.codes[0]), JSON.stringify(inv));
  ok('invitaciones: hace falta ser entrenador', (await api({ op: 'a_invite', token: 'x.y.z', n: 1 })).err === 'sesion');
  const reg = { op: 'register', email: 'ana@ejemplo.com', auth: A, invite: inv.codes[0], consent: { adult: true, terms: true, health: false }, wrapUser: 'WU', wrapCoach: 'WC', kid: 'k1', blob: 'BLOB1' };
  ok('registro sin consentimiento: rechazado', (await api({ ...reg, consent: { adult: true, terms: false } })).err === 'consentimiento');
  ok('registro con invitación falsa', (await api({ ...reg, invite: 'EP-AAAA-AAAA' })).err === 'invitacion');
  ok('registro con correo raro', (await api({ ...reg, email: '=1+1@x.com' })).err === 'datos');
  const r1 = await api(reg); ok('registro', r1.ok && r1.rev === 1 && !!r1.token, JSON.stringify(r1));
  ok('la invitación no se puede reutilizar', (await api({ ...reg, email: 'otra@ejemplo.com' })).err === 'invitacion');
  ok('correo repetido', (await api({ ...reg, invite: inv.codes[1] })).err === 'existe');
  ok('entrada con contraseña mala', (await api({ op: 'login', email: 'ana@ejemplo.com', auth: B })).err === 'credenciales');
  ok('entrada con correo que no existe: mismo error', (await api({ op: 'login', email: 'nadie@ejemplo.com', auth: A })).err === 'credenciales');
  const l1 = await api({ op: 'login', email: 'ana@ejemplo.com', auth: A }); ok('entrada', l1.ok && l1.blob === 'BLOB1' && l1.wrapUser === 'WU' && l1.rev === 1 && l1.health === false && l1.ckid === 'k1');
  const big = 'x'.repeat(130000); const s1 = await api({ op: 'save', token: l1.token, rev: 1, blob: big, health: true, hset: true });
  const sx = await api({ op: 'save', token: l1.token, rev: 2, blob: 'x', health: false }); ok('un dispositivo que no sabe que cambió el consentimiento de salud no puede guardar', sx.conflict === true && sx.health === true && sx.rev === 2, JSON.stringify(sx).slice(0, 80));
  ok('guardar datos grandes (varias celdas)', s1.ok && s1.rev === 2, JSON.stringify(s1));
  const ld = await api({ op: 'load', token: l1.token }); ok('cargar devuelve lo mismo', ld.blob === big && ld.rev === 2 && ld.health === true);
  const c1 = await api({ op: 'save', token: l1.token, rev: 1, blob: 'viejo' }); ok('guardar desde una versión antigua: conflicto con los datos actuales', c1.conflict === true && c1.rev === 2 && c1.blob === big);
  const s2 = await api({ op: 'save', token: l1.token, rev: 2, blob: 'corto', health: true }); const ld2 = await api({ op: 'load', token: l1.token }); ok('al acortar no quedan restos', s2.rev === 3 && ld2.blob === 'corto');
  ok('sesión falsificada', (await api({ op: 'load', token: l1.token.replace(/.$/, '0') + '1' })).err === 'sesion');
  ok('la sesión de usuario no vale de entrenador', (await api({ op: 'a_list', token: l1.token })).err === 'sesion');
  ok('la sesión de entrenador no vale de usuario', (await api({ op: 'load', token: al.token })).err === 'sesion');
  const list = await api({ op: 'a_list', token: al.token }); ok('lista del entrenador', list.users.length === 1 && list.users[0].email === 'ana@ejemplo.com' && /datos de salud: sí/.test(list.users[0].consent) && list.invites.filter(i => i.usedBy).length === 1, JSON.stringify(list.users));
  const g = await api({ op: 'a_get', token: al.token, id: list.users[0].id }); ok('entrenador recibe los datos cifrados y la llave envuelta', g.blob === 'corto' && g.wrapCoach === 'WC');
  ok('cambio de contraseña: la actual mala', (await api({ op: 'passwd', token: l1.token, auth: B, next: B, wrapUser: 'WU2' })).err === 'credenciales');
  const pw = await api({ op: 'passwd', token: l1.token, auth: A, next: B, wrapUser: 'WU2' });
  ok('cambio de contraseña: da sesión nueva y la anterior deja de valer', pw.ok && !!pw.token && (await api({ op: 'load', token: l1.token })).err === 'sesion' && (await api({ op: 'load', token: pw.token })).ok);
  const l2 = await api({ op: 'login', email: 'ana@ejemplo.com', auth: B }); ok('entra con la nueva y no con la vieja', l2.ok && l2.wrapUser === 'WU2' && (await api({ op: 'login', email: 'ana@ejemplo.com', auth: A })).err === 'credenciales');
  const slept = async () => (await (await fetch(base + '/__dump')).json()).stats.slept;
  await fetch(base + '/__clearcache'); const s0 = await slept();
  for (let i = 0; i < 10; i++) await api({ op: 'login', email: 'ana@ejemplo.com', auth: A });
  ok('10 fallos seguidos: todavía sin retraso', (await slept()) === s0);
  await api({ op: 'login', email: 'ana@ejemplo.com', auth: A }); ok('a partir de ahí cada fallo se retrasa', (await slept()) === s0 + 3000);
  ok('…y la contraseña buena sigue entrando (no se puede dejar fuera al dueño)', (await api({ op: 'login', email: 'ana@ejemplo.com', auth: B })).ok);
  ok('invitación vacía o con otra forma: rechazada', (await api({ ...reg, email: 'x@ejemplo.com', invite: ' ' })).err === 'datos' || (await api({ ...reg, email: 'x@ejemplo.com', invite: ' ' })).err === 'invitacion');
  ok('invitación «EP» sin más: rechazada', (await api({ ...reg, email: 'x@ejemplo.com', invite: 'EP' })).err === 'invitacion');
  await fetch(base + '/__clearcache');
  const dump = await (await fetch(base + '/__dump')).json();
  ok('en la hoja no hay contraseñas ni la llave del entrenador en claro', !JSON.stringify(dump.sheets).includes(A) && !JSON.stringify(dump.sheets).includes(B) && !JSON.stringify(dump.sheets).includes(ADM));
  ok('borrar cuenta: contraseña mala', (await api({ op: 'remove', token: l2.token, auth: A })).err === 'credenciales');
  ok('borrar cuenta', (await api({ op: 'remove', token: l2.token, auth: B })).ok && (await api({ op: 'load', token: l2.token })).err === 'sesion');
  const list2 = await api({ op: 'a_list', token: al.token }); ok('la fila desaparece de la hoja y el correo se borra de las invitaciones', list2.users.length === 0 && !JSON.stringify(list2.invites).includes('ana@ejemplo.com'), JSON.stringify(list2.invites));
  const r2 = await api({ ...reg, email: 'luis@ejemplo.com', invite: inv.codes[1] }); const list3 = await api({ op: 'a_list', token: al.token });
  ok('el entrenador puede borrar una cuenta', (await api({ op: 'a_delete', token: al.token, id: list3.users[0].id })).ok && (await api({ op: 'load', token: r2.token })).err === 'sesion');
} finally { srv.kill(); }
console.log(fails ? '\n' + fails + ' fallos' : '\ntodo bien'); process.exit(fails ? 1 : 0);
