// Pruebas del servidor (sin navegador): registro, entrada, guardar, conflictos, límites y entrenador.
import { spawn } from 'node:child_process';
const port = 8790, base = 'http://localhost:' + port, srv = spawn('node', [new URL('./servidor_prueba.mjs', import.meta.url).pathname, '.', String(port)], { stdio: 'ignore' });
await new Promise(r => setTimeout(r, 700));
let fails = 0; const ok = (n, c, x = '') => { console.log((c ? 'OK    ' : 'FALLA ') + n + (c ? '' : '  → ' + x)); if (!c) fails++; };
const api = async b => (await fetch(base + '/api', { method: 'POST', body: JSON.stringify(b) })).json();
const A = 'a'.repeat(64), B = 'b'.repeat(64), ADM = 'c'.repeat(64);
try {
  ok('sin configurar: no hay clave pública', (await api({ op: 'pub' })).err === 'sin_configurar');
  ok('operación desconocida', (await api({ op: 'constructor' })).err === 'op' && (await api({ op: 'nada' })).err === 'op');
  const setup = await (await fetch(base + '/__setup')).text();
  ok('puesta en marcha: código malo', (await api({ op: 'a_setup', setup: 'x', auth: ADM, salt: 's', pub: '{}', priv: 'p', kid: 'k1' })).err === 'codigo');
  const st = await api({ op: 'a_setup', setup, auth: ADM, salt: 's1', pub: '{"kty":"RSA"}', priv: 'PRIV', kid: 'k1' });
  ok('puesta en marcha con el código', st.ok && !!st.token);
  ok('el código solo sirve una vez', (await api({ op: 'a_setup', setup, auth: ADM, salt: 's', pub: '{}', priv: 'p', kid: 'k2' })).err === 'codigo');
  const hello = await api({ op: 'a_hello' }); ok('a_hello', hello.configured === true && hello.salt === 's1');
  ok('entrenador: contraseña mala', (await api({ op: 'a_login', auth: B })).err === 'credenciales');
  const al = await api({ op: 'a_login', auth: ADM }); ok('entrenador: entra y recibe su llave cifrada', al.ok && al.priv === 'PRIV' && al.kid === 'k1');
  const inv = await api({ op: 'a_invite', token: al.token, n: 3 }); ok('3 invitaciones', inv.ok && inv.codes.length === 3 && /^EP-[A-Z2-9]{4}-[A-Z2-9]{4}$/.test(inv.codes[0]), JSON.stringify(inv));
  ok('invitaciones: hace falta ser entrenador', (await api({ op: 'a_invite', token: 'x.y.z', n: 1 })).err === 'sesion');
  const reg = { op: 'register', email: 'ana@ejemplo.com', auth: A, invite: inv.codes[0], consent: { adult: true, terms: true, health: false }, wrapUser: 'WU', wrapCoach: 'WC', kid: 'k1', blob: 'BLOB1' };
  ok('registro sin consentimiento: rechazado', (await api({ ...reg, consent: { adult: true, terms: false } })).err === 'consentimiento');
  ok('registro con invitación falsa', (await api({ ...reg, invite: 'EP-AAAA-AAAA' })).err === 'invitacion');
  ok('registro con correo raro', (await api({ ...reg, email: '=1+1@x.com' })).err === 'datos');
  const r1 = await api(reg); ok('registro', r1.ok && r1.rev === 1 && !!r1.token, JSON.stringify(r1));
  ok('la invitación no se puede reutilizar', (await api({ ...reg, email: 'otra@ejemplo.com' })).err === 'invitacion');
  ok('correo repetido con otra contraseña', (await api({ ...reg, auth: B, invite: inv.codes[1] })).err === 'existe');
  const again = await api(reg); ok('registro repetido con los mismos datos (respuesta perdida): entra en la cuenta ya creada', again.ok && again.existing === true && again.rev === 1 && !!again.token, JSON.stringify(again));
  await fetch(base + '/__busy?on=1');
  ok('con el turno ocupado, escribir contesta «ocupado»', (await api({ op: 'save', token: r1.token, rev: 1, blob: 'x' })).err === 'ocupado');
  ok('…pero leer y entrar siguen funcionando', (await api({ op: 'load', token: r1.token })).ok && (await api({ op: 'pub' })).ok && (await api({ op: 'login', email: 'ana@ejemplo.com', auth: A })).ok);
  await fetch(base + '/__busy?on=0');
  ok('entrada con contraseña mala', (await api({ op: 'login', email: 'ana@ejemplo.com', auth: B })).err === 'credenciales');
  ok('entrada con correo que no existe: mismo error', (await api({ op: 'login', email: 'nadie@ejemplo.com', auth: A })).err === 'credenciales');
  const l1 = await api({ op: 'login', email: 'ana@ejemplo.com', auth: A }); ok('entrada', l1.ok && l1.blob === 'BLOB1' && l1.wrapUser === 'WU' && l1.rev === 1 && l1.health === false && l1.ckid === 'k1');
  const big = 'x'.repeat(130000); const s1 = await api({ op: 'save', token: l1.token, rev: 1, blob: big, health: true, hset: true });
  const sx = await api({ op: 'save', token: l1.token, rev: 2, blob: 'x', health: false }); ok('un dispositivo que no sabe que cambió el consentimiento de salud no puede guardar', sx.conflict === true && sx.health === true && sx.rev === 2, JSON.stringify(sx).slice(0, 80));
  ok('guardar datos grandes (varias celdas)', s1.ok && s1.rev === 2, JSON.stringify(s1));
  const ld = await api({ op: 'load', token: l1.token }); ok('cargar devuelve lo mismo', ld.blob === big && ld.rev === 2 && ld.health === true);
  const c1 = await api({ op: 'save', token: l1.token, rev: 1, blob: 'viejo' }); ok('guardar desde una versión antigua: conflicto con los datos actuales', c1.conflict === true && c1.rev === 2 && c1.blob === big);
  const s2 = await api({ op: 'save', token: l1.token, rev: 2, blob: 'corto', health: true }); const ld2 = await api({ op: 'load', token: l1.token }); ok('al acortar no quedan restos', s2.rev === 3 && ld2.blob === 'corto');
  ok('sesión falsificada', (await api({ op: 'load', token: l1.token.replace(/.$/, '0') + '1' })).err === 'sesion');
  ok('la sesión de usuario no vale de entrenador', (await api({ op: 'a_list', token: l1.token })).err === 'sesion');
  ok('la sesión de entrenador no vale de usuario', (await api({ op: 'load', token: al.token })).err === 'sesion');
  const list = await api({ op: 'a_list', token: al.token }); ok('lista del entrenador', list.users.length === 1 && list.users[0].email === 'ana@ejemplo.com' && /datos de salud: sí/.test(list.users[0].consent) && list.invites.filter(i => i.usedBy).length === 1, JSON.stringify(list.users));
  const g = await api({ op: 'a_get', token: al.token, id: list.users[0].id }); ok('entrenador recibe los datos cifrados y la llave envuelta', g.blob === 'corto' && g.wrapCoach === 'WC');
  ok('cambio de contraseña: la actual mala', (await api({ op: 'passwd', token: l1.token, auth: B, next: B, wrapUser: 'WU2' })).err === 'credenciales');
  const pw = await api({ op: 'passwd', token: l1.token, auth: A, next: B, wrapUser: 'WU2' });
  ok('cambio de contraseña: da sesión nueva y la anterior deja de valer', pw.ok && !!pw.token && (await api({ op: 'load', token: l1.token })).err === 'sesion' && (await api({ op: 'load', token: pw.token })).ok);
  const l2 = await api({ op: 'login', email: 'ana@ejemplo.com', auth: B }); ok('entra con la nueva y no con la vieja', l2.ok && l2.wrapUser === 'WU2' && (await api({ op: 'login', email: 'ana@ejemplo.com', auth: A })).err === 'credenciales');
  // --- contraseña olvidada
  const mails = async () => (await (await fetch(base + '/__dump')).json()).stats.mail;
  ok('pedir código para un correo sin cuenta: contesta igual y no envía nada', (await api({ op: 'reset_ask', email: 'nadie@ejemplo.com' })).ok && (await mails()).length === 0);
  ok('pedir código: llega un correo a esa cuenta', (await api({ op: 'reset_ask', email: 'ana@ejemplo.com' })).ok && (await mails()).length === 1 && (await mails())[0].to === 'ana@ejemplo.com');
  const code = ((await mails())[0].body.match(/\b(\d{6})\b/) || [])[1]; ok('el correo trae un código de 6 cifras', /^\d{6}$/.test(code || ''));
  const dumpR = await (await fetch(base + '/__dump')).json(); ok('el código no queda legible en la hoja', !JSON.stringify(dumpR.sheets).includes(code));
  const C2 = 'd'.repeat(64);
  ok('código equivocado: rechazado', (await api({ op: 'reset_do', email: 'ana@ejemplo.com', code: code === '000000' ? '111111' : '000000', auth: C2, wrapUser: 'WU3' })).err === 'codigo');
  const rs = await api({ op: 'reset_do', email: 'ana@ejemplo.com', code: code.slice(0, 3) + ' ' + code.slice(3), auth: C2, wrapUser: 'WU3' });
  ok('código bueno: contraseña nueva, sesión nueva y los datos intactos', rs.ok && !!rs.token && (await api({ op: 'load', token: rs.token })).blob === 'corto', JSON.stringify(rs).slice(0, 90));
  ok('la sesión anterior deja de valer y la contraseña vieja también', (await api({ op: 'load', token: l2.token })).err === 'sesion' && (await api({ op: 'login', email: 'ana@ejemplo.com', auth: B })).err === 'credenciales');
  const l3 = await api({ op: 'login', email: 'ana@ejemplo.com', auth: C2 }); ok('se entra con la nueva y recibe la llave guardada con ella', l3.ok && l3.wrapUser === 'WU3');
  ok('el código solo vale una vez', (await api({ op: 'reset_do', email: 'ana@ejemplo.com', code, auth: C2, wrapUser: 'WU4' })).err === 'codigo');
  await api({ op: 'reset_ask', email: 'ana@ejemplo.com' }); const code2 = ((await mails())[1].body.match(/\b(\d{6})\b/) || [])[1];
  for (let i = 0; i < 5; i++) await api({ op: 'reset_do', email: 'ana@ejemplo.com', code: '999999' === code2 ? '888888' : '999999', auth: C2, wrapUser: 'x' });
  ok('tras 5 intentos fallidos ese código queda anulado', (await api({ op: 'reset_do', email: 'ana@ejemplo.com', code: code2, auth: C2, wrapUser: 'x' })).err === 'codigo');
  await api({ op: 'reset_ask', email: 'ana@ejemplo.com' }); const before = (await mails()).length; await api({ op: 'reset_ask', email: 'ana@ejemplo.com' });
  ok('máximo 3 códigos por correo cada media hora', before === 3 && (await mails()).length === 3);
  await fetch(base + '/__clearcache'); await api({ op: 'reset_ask', email: 'ana@ejemplo.com' }); const code3 = ((await mails())[3].body.match(/\b(\d{6})\b/) || [])[1];
  const rs2 = await api({ op: 'reset_do', email: 'ana@ejemplo.com', code: code3, auth: B, wrapUser: 'WU5', wrapCoach: 'WC5', kid: 'k1', blob: 'NUEVO' });
  const ld5 = await api({ op: 'load', token: rs2.token }); ok('sin la llave antigua: la cuenta sigue con los datos nuevos que manda el dispositivo y sin salud', rs2.ok && ld5.blob === 'NUEVO' && ld5.health === false && rs2.rev === ld5.rev, JSON.stringify(ld5));
  await fetch(base + '/__clearcache');
  const slept = async () => (await (await fetch(base + '/__dump')).json()).stats.slept;
  await fetch(base + '/__clearcache'); const s0 = await slept();
  for (let i = 0; i < 10; i++) await api({ op: 'login', email: 'ana@ejemplo.com', auth: A });
  ok('10 fallos seguidos: todavía sin retraso', (await slept()) === s0);
  await api({ op: 'login', email: 'ana@ejemplo.com', auth: A }); ok('a partir de ahí cada fallo se retrasa', (await slept()) === s0 + 3000);
  ok('…y la contraseña buena sigue entrando (no se puede dejar fuera al dueño)', (await api({ op: 'login', email: 'ana@ejemplo.com', auth: B })).ok);
  ok('invitación vacía o con otra forma: rechazada', (await api({ ...reg, email: 'x@ejemplo.com', invite: ' ' })).err === 'datos' || (await api({ ...reg, email: 'x@ejemplo.com', invite: ' ' })).err === 'invitacion');
  ok('invitación «EP» sin más: rechazada', (await api({ ...reg, email: 'x@ejemplo.com', invite: 'EP' })).err === 'invitacion');
  await fetch(base + '/__clearcache');
  const dump = await (await fetch(base + '/__dump')).json();
  ok('en la hoja no hay contraseñas ni la llave del entrenador en claro', !JSON.stringify(dump.sheets).includes(A) && !JSON.stringify(dump.sheets).includes(B) && !JSON.stringify(dump.sheets).includes(ADM));
  // IA: puente con la API, solo con sesión, con la clave del servidor y con límite diario
  const um = [{ role: 'user', content: [{ type: 'text', text: 'hola' }] }], gai = async q => fetch(base + '/__ai?' + q);
  ok('IA sin clave puesta: no está activa', (await api({ op: 'ai', token: rs2.token, messages: um })).err === 'sin_ia' && (await api({ op: 'load', token: rs2.token })).ai === false);
  await gai('key=sk-prueba-123&text=' + encodeURIComponent('respuesta de prueba'));
  ok('IA sin sesión: rechazada', (await api({ op: 'ai', token: 'x', messages: um })).err === 'sesion');
  const a1 = await api({ op: 'ai', token: rs2.token, system: 'eres dietista', messages: [{ role: 'user', content: [{ type: 'image', media_type: 'image/jpeg', data: 'QUJD' }, { type: 'text', text: 'qué es' }] }] });
  let dai = (await (await fetch(base + '/__dump')).json()).stats.ai.at(-1);
  ok('IA: devuelve el texto y avisa de que está activa', a1.ok && a1.text === 'respuesta de prueba' && (await api({ op: 'load', token: rs2.token })).ai === true, JSON.stringify(a1));
  ok('IA: la petición sale con la clave del servidor, el modelo y la foto', dai.key === 'sk-prueba-123' && /api\.anthropic\.com\/v1\/messages$/.test(dai.url) && /^claude-/.test(dai.body.model) && dai.body.system === 'eres dietista' && dai.body.messages[0].content[0].source.data === 'QUJD' && dai.body.max_tokens <= 1500, JSON.stringify(dai).slice(0, 300));
  ok('IA: la clave no viaja al cliente ni queda en la hoja', !JSON.stringify(a1).includes('sk-prueba') && !JSON.stringify((await (await fetch(base + '/__dump')).json()).sheets).includes('sk-prueba'));
  ok('IA: peticiones mal formadas', (await api({ op: 'ai', token: rs2.token, messages: [] })).err === 'datos' && (await api({ op: 'ai', token: rs2.token, messages: [{ role: 'system', content: [{ type: 'text', text: 'x' }] }] })).err === 'datos' && (await api({ op: 'ai', token: rs2.token, messages: [{ role: 'user', content: [{ type: 'image', media_type: 'image/svg+xml', data: 'QUJD' }] }] })).err === 'datos');
  await gai('code=529'); ok('IA saturada: lo dice', (await api({ op: 'ai', token: rs2.token, messages: um })).err === 'ia_ocupada'); await gai('code=200');
  await gai('max=2'); ok('IA: límite diario por persona', (await api({ op: 'ai', token: rs2.token, messages: um })).err === 'limite_ia'); await gai('max=60');
  ok('borrar cuenta: contraseña mala', (await api({ op: 'remove', token: rs2.token, auth: A })).err === 'credenciales');
  ok('borrar cuenta', (await api({ op: 'remove', token: rs2.token, auth: B })).ok && (await api({ op: 'load', token: rs2.token })).err === 'sesion');
  const list2 = await api({ op: 'a_list', token: al.token }); ok('la fila desaparece de la hoja y el correo se borra de las invitaciones', list2.users.length === 0 && !JSON.stringify(list2.invites).includes('ana@ejemplo.com'), JSON.stringify(list2.invites));
  const r2 = await api({ ...reg, email: 'luis@ejemplo.com', invite: inv.codes[1] }); const list3 = await api({ op: 'a_list', token: al.token });
  ok('el entrenador puede borrar una cuenta', (await api({ op: 'a_delete', token: al.token, id: list3.users[0].id })).ok && (await api({ op: 'load', token: r2.token })).err === 'sesion');
} finally { srv.kill(); }
console.log(fails ? '\n' + fails + ' fallos' : '\ntodo bien'); process.exit(fails ? 1 : 0);
